# Generated by Django 4.1 on 2022-08-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='jobtype',
            field=models.CharField(choices=[('UI', 'UI'), ('UX', 'UX'), ('FE', 'Front End'), ('BE', 'Back End'), ('FS', 'Full Stack'), ('RE', 'Refactor')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='contract',
            name='price',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
