# Generated by Django 4.1 on 2022-08-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contract_jobtype_contract_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='jobtype',
        ),
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.CharField(max_length=8),
        ),
    ]
