# Generated by Django 4.1 on 2022-08-24 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_bid', models.BooleanField(default=False)),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bid')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contract')),
            ],
        ),
    ]
