# Generated by Django 4.1 on 2022-08-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contractbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractbid',
            name='can_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='contract_ref',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='can_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractbid',
            name='status',
            field=models.CharField(choices=[('PL', 'Planning'), ('PI', 'Pitching'), ('SV', 'Server'), ('CL', 'Client'), ('MV', 'MVP'), ('ST', 'Styling'), ('CM', 'Complete')], default=None, max_length=2),
        ),
    ]
