# Generated by Django 4.1 on 2022-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_contractbid_can_bid_bid_contract_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='can_bid',
            field=models.BooleanField(default=True),
        ),
    ]
